version: "2"
services:
  web:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "9000:9000"
      - "5858:5858"
    links:
      - "mongo"
  debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8080:8080"
    links:
      - "web"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "/data/db:/data/db"